version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Benfica2003@
      MYSQL_DATABASE: unistak_sir
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql

